### ISSUE TITLE
Bug: UxAS ignores EligibleEntities in LineSearchTask

### ISSUE THREAD

**Issue by sahabi** [afrl-rq/OpenUxAS-SoI#29]
When an entity is specified for LineSearchTask, the task doesn't get assigned to any UAV. However, if we leave the EligibleEntities field empty, the task will be assigned successfully to an available UAV. 

We tried the same thing with PointSearchTask and the behavior was correct, as in the task was assigned successfully to an entity that is specified under the EligibleEntities field in task's message.

**Comment by derekkingston** [comment]
This bug could not be duplicated. Upon further investigation, the XML description of the LineSearchTask was mal-formed (`<int64>1000/<int64>` when it should have been `<int64>1000</int64>`). An additional automated test was added in commit 4fea9f66 to ensure that line search tasks properly handle vehicle eligibility.
