### ISSUE TITLE
Problem Decoding LMCP Messages using Python

### ISSUE THREAD

**Issue by sahabi** [afrl-rq/OpenUxAS-SoI#43]
When attempting to receive LMCP messages from UxAS or AMASE, most received messages are not decoded properly using LMCPFactory.py. None is returned instead of an LMCP object. 

My scripts works fine with an old AMASE version (however, I can't use the old AMASE version as it's incompatible with UxAS), so I suspect the issue is in AMASE and UxAS or just AMASE since some of the messages coming from UxAS are decoded properly.

**Comment by derekkingston** [comment]
The Python LMCP code has been significantly re-designed and external logging examples provided (see `examples/02_Example_WaterwaySearch/ext_logger/ext_logger.py`). Compatibility between AMASE, UxAS, and external Python programs should now be working.
