### ISSUE TITLE
MacOS Build Problem - meson.build not found

### ISSUE THREAD

**Issue by wardpage** [afrl-rq/OpenUxAS-SoI#47]
Got to the following build step without a problem (step 2 in Building from the Command Line):
meson build --buildtype=release

Seems to build most of it ok. First time it failed with an 'Error 403' message. Here's the current build feedback:

Mazer-2:OpenUxAS wpage$ meson build --buildtype=release
The Meson build system
Version: 0.42.1
Source dir: /Users/wpage/Dev/Sim/OpenUxAS
Build dir: /Users/wpage/Dev/Sim/OpenUxAS/build
Build type: native build
Project name: UxAS
Native C compiler: cc (clang 8.1.0)
Native C++ compiler: c++ (clang 8.1.0)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Using zeromq from cache.

Executing subproject zeromq.

Project name: zeromq
Native C++ compiler: c++ (clang 8.1.0)
Has header "alloca.h": YES
Has header "arpa/inet.h": YES
Has header "dlfcn.h": YES
Has header "errno.h": YES
Has header "ifaddrs.h": YES
Has header "inttypes.h": YES
Has header "limits.h": YES
Has header "memory.h": YES
Has header "netinet/in.h": YES
Has header "netinet/tcp.h": YES
Has header "stdbool.h": YES
Has header "stddef.h": YES
Has header "stdint.h": YES
Has header "stdlib.h": YES
Has header "strings.h": YES
Has header "string.h": YES
Has header "sys/eventfd.h": NO
Has header "sys/socket.h": YES
Has header "sys/stat.h": YES
Has header "sys/time.h": YES
Has header "sys/types.h": YES
Has header "sys/uio.h": YES
Has header "time.h": YES
Has header "unistd.h": YES
Has header "windows.h": NO
Has header "sys/uio.h": YES
Checking if "kqueue links" links: YES
Checking for function "clock_gettime": YES
Checking for function "fork": YES
Checking for function "gettimeofday": YES
Checking for function "gss_init_sec_context": NO
Checking for function "memset": YES
Checking for function "socket": YES
Found pkg-config: /usr/local/bin/pkg-config (0.29.2)
Dependency libsodium found: NO
Header <stdbool.h> has symbol "_Bool": YES
Dependency threads found: YES
Configuring platform.hpp using configuration
Build targets in project: 1

Subproject zeromq finished.
Using czmq from cache.

Executing subproject czmq.

Project name: czmq
Native C compiler: cc (clang 8.1.0)
Has header "arpa/inet.h": YES
Has header "dlfcn.h": YES
Has header "errno.h": YES
Has header "ifaddrs.h": YES
Has header "inttypes.h": YES
Has header "limits.h": YES
Has header "linux/wireless.h": NO
Has header "memory.h": YES
Has header "netinet/in.h": YES
Has header "netinet/tcp.h": YES
Has header "net/if.h": YES
Has header "net/if/media.h": NO
Has header "stdbool.h": YES
Has header "stddef.h": YES
Has header "stdint.h": YES
Has header "stdlib.h": YES
Has header "strings.h": YES
Has header "string.h": YES
Has header "sys/socket.h": YES
Has header "sys/stat.h": YES
Has header "sys/time.h": YES
Has header "sys/types.h": YES
Has header "unistd.h": YES
Has header "windows.h": NO
Header <stdbool.h> has symbol "_Bool": YES
Checking for function "getifaddrs": YES
Checking for function "gettimeofday": YES
Checking for function "memset": YES
Configuring platform.h using configuration
Build targets in project: 2

Subproject czmq finished.
Using cppzmq from cache.

Executing subproject cppzmq.

Project name: cppzmq
Native C++ compiler: c++ (clang 8.1.0)
Build targets in project: 3

Subproject cppzmq finished.
Using zyre from cache.

Executing subproject zyre.

Project name: zyre
Native C compiler: cc (clang 8.1.0)
Build targets in project: 4

Subproject zyre finished.
Using sqlite3 from cache.

Executing subproject sqlite3.

Project name: sqlite3
Native C compiler: cc (clang 8.1.0)
Build targets in project: 5

Subproject sqlite3 finished.
Using sqlitecpp from cache.

Executing subproject sqlitecpp.

Project name: sqlitecpp
Native C++ compiler: c++ (clang 8.1.0)
Build targets in project: 6

Subproject sqlitecpp finished.
Using zlib from cache.

Executing subproject zlib.

Project name: zlib
Native C compiler: cc (clang 8.1.0)
Build targets in project: 7

Subproject zlib finished.
Using minizip from cache.

Executing subproject minizip.

Project name: minizip
Native C compiler: cc (clang 8.1.0)
Build targets in project: 8

Subproject minizip finished.
Dependency Boost (filesystem, regex, system) found: YES 1.65.1, /usr/local

Executing subproject TinyGPS.

Project name: TinyGPS
Native C++ compiler: c++ (clang 8.1.0)
Build targets in project: 9

Subproject TinyGPS finished.
Using serial from cache.

Executing subproject serial.

Project name: serial
Native C++ compiler: c++ (clang 8.1.0)
Build targets in project: 10

Subproject serial finished.

Executing subproject PugiXML.

Project name: PugiXML
Native C++ compiler: c++ (clang 8.1.0)
Build targets in project: 11

Subproject PugiXML finished.
Configuring config.h using configuration
Dependency glu found: NO
Checking for function "gluNewTess": YES
Checking for function "gluDeleteTess": YES
Checking for function "gluErrorString": YES
Using gtest from cache.

Executing subproject gtest.

Meson encountered an error in file tests/meson.build, line 1, column 0:
Missing Meson file in /Users/wpage/Dev/Sim/OpenUxAS/3rd/googletest-release-1.8.0/meson.build

Any help is greatly appreciated.

**Comment by derekkingston** [comment]
Your build is failing when Meson is attempting to download Google Test. This is most likely due to the "wrapper" manager at <https://wrapdb.mesonbuild.com/gtest> not being accessible (the wrapdb website can be flaky). Unfortunately the error message is not very interpret-able.

I'll use this issue to update UxAS to download google test directly without relying on wrapdb. However, you should be able to re-run 'meson build' after confirming that <https://wrapdb.mesonbuild.com/gtest> can be reached and then you should be able to continue.

**Comment by wardpage** [comment]
Derek,

Thanks!  I got it figured out.  My firewall was blocking the wrapdb site.  I’m up and running.  Are there any good tutorials for developers?  In particular, I don’t see anything on the XML fields for setting up scenarios.  Any help is greatly appreciated.

Ward

Ward Page
DZYNE Technologies
2751 Prosperity Ave.  Suite 520
Fairfax, VA  22031
dzynetech.com<http://dzynetech.com>
wpage@dzynetech.com<mailto:wpage@dzynetech.com>
703.314.5978






On Nov 13, 2017, at 11:42 AM, Derek Kingston <notifications@github.com<mailto:notifications@github.com>> wrote:


Your build is failing when Meson is attempting to download Google Test. This is most likely due to the "wrapper" manager at https://wrapdb.mesonbuild.com/gtest not being accessible (the wrapdb website can be flaky). Unfortunately the error message is not very interpret-able.

I'll use this issue to update UxAS to download google test directly without relying on wrapdb. However, you should be able to re-run 'meson build' after confirming that https://wrapdb.mesonbuild.com/gtest can be reached and then you should be able to continue.

**Comment by derekkingston** [comment]
[UxAS_UserManual.pdf](https://github.com/afrl-rq/OpenUxAS/files/1468344/UxAS_UserManual.pdf)
Suggest starting with Chapter 5 in the UxAS manual and the OpenAMASE documentation. The main notion is that everything in the system (and scenario) is described by an LMCP message. The LMCP reference documentation is automatically create at OpenUxAS/doc/LMCP/index.html if you use 'RunLmcpGen.sh'.

**Comment by wardpage** [comment]
Derek,

Thanks!

Ward

Ward's interweb doohicky

On Nov 13, 2017, at 15:37, Derek Kingston <notifications@github.com<mailto:notifications@github.com>> wrote:


UxAS_UserManual.pdf<https://github.com/afrl-rq/OpenUxAS/files/1468344/UxAS_UserManual.pdf>
Suggest starting with Chapter 5 in the UxAS manual and the OpenAMASE documentation. The main notion is that everything in the system (and scenario) is described by an LMCP message. The LMCP reference documentation is automatically create at OpenUxAS/doc/LMCP/index.html if you use 'RunLmcpGen.sh'.

-

**Comment by derekkingston** [comment]
The latest version of UxAS on the 'develop' branch (3c2eaf83) as of 17 Jan 2018 incorporates a direct download of Google Test with locally provided meson patch. So there's no longer a reliance on 'wrapdb' to be allowed through a firewall.
