### ISSUE TITLE
Need a place for architecture models

### ISSUE THREAD

**Issue by jendavis** [afrl-rq/OpenUxAS-SoI#5]
The Architecture team needs a version controlled place to store our architecture models. Let us know where you want us to put those.

**Comment by backesj** [comment]
I suggest we make a new repository within the afrl-rq group.

**Comment by derekkingston** [comment]
@acfoltzer is looking into creating a Git LFS repo for this.

**Comment by jendavis** [comment]
I don't expect us to have large files--mostly just AADL (text) files. I already talked to @acfoltzer about that.

**Comment by jendavis** [comment]
@acfoltzer suggested we work under OpenUxAS, possibly on a fork or branch. I'm waiting for the documentation on recommended practices for forking and branching to come out before putting anything on GitHub.

**Comment by derekkingston** [comment]
I added an `architecture` branch on OpenUxAS. Let use that for now - I believe forks will make our continuous integration approach more difficult.

**Comment by jendavis** [comment]
OK, thanks
