### ISSUE TITLE
meson.py build --backend=vs error. Incorrect hash for source minizip:

### ISSUE THREAD

**Issue by leedh0124** [afrl-rq/OpenUxAS-SoI#55]
Hi, I'm sorta stuck in Step 9. Prepare Build. (Im doing this on Windows btw) 
I get the following error message.. 

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.5.2
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\OpenUxAS>meson.py build --backend=vs
The Meson build system
Version: 0.41.0
Source dir: C:\OpenUxAS
Build dir: C:\OpenUxAS\build
Build type: native build
Auto detected Visual Studio backend: vs2017
Project name: UxAS
Native c compiler: cl (msvc 19.12.25831)
Native cpp compiler: cl (msvc 19.12.25831)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Downloading zeromq from https://github.com/zeromq/zeromq4-1/releases/download/v4.1.6/zeromq-4.1.6.zip
Download size: 1240860
Downloading: ..........
Downloading patch from file:///C:/OpenUxAS/3rd/zeromq-4.1.6_patch.tar
Download size: 20480
Downloading: ..........

Executing subproject zeromq.

Project name: zeromq
Native cpp compiler: cl (msvc 19.12.25831)
Library Advapi32 found: YES
Library Ws2_32 found: YES
Library Rpcrt4 found: YES
Has header "alloca.h": NO
Has header "arpa/inet.h": NO
Has header "dlfcn.h": NO
Has header "errno.h": YES
Has header "ifaddrs.h": NO
Has header "inttypes.h": YES
Has header "limits.h": YES
Has header "memory.h": YES
Has header "netinet/in.h": NO
Has header "netinet/tcp.h": NO
Has header "stdbool.h": YES
Has header "stddef.h": YES
Has header "stdint.h": YES
Has header "stdlib.h": YES
Has header "strings.h": NO
Has header "string.h": YES
Has header "sys/eventfd.h": NO
Has header "sys/socket.h": NO
Has header "sys/stat.h": YES
Has header "sys/time.h": NO
Has header "sys/types.h": YES
Has header "sys/uio.h": NO
Has header "time.h": YES
Has header "unistd.h": NO
Has header "windows.h": YES
Has header "sys/uio.h": NO
Checking if "kqueue links" links: NO
Checking if "epoll runs" runs: DID NOT COMPILE
Checking if "devpoll links" links: NO
Checking if "poll links" links: NO
Checking if "select links" links: NO
Checking for function "clock_gettime": NO
Checking for function "fork": NO
Checking for function "gettimeofday": NO
Checking for function "gss_init_sec_context": NO
Checking for function "memset": YES
Checking for function "socket": NO
Found Pkg-config: NO
Dependency libsodium found: NO
Header <stdbool.h> has symbol "_Bool": NO
Dependency threads found: YES
Configuring platform.hpp using configuration
Build targets in project: 1

Subproject zeromq finished.
Downloading czmq from https://github.com/zeromq/czmq/archive/v3.0.1.zip
Downloading file of unknown size.
Downloading patch from file:///C:/OpenUxAS/3rd/czmq-3.0.1_patch.tar
Download size: 61440
Downloading: ..........

Executing subproject czmq.

Project name: czmq
Native c compiler: cl (msvc 19.12.25831)
Has header "arpa/inet.h": NO
Has header "dlfcn.h": NO
Has header "errno.h": YES
Has header "ifaddrs.h": NO
Has header "inttypes.h": YES
Has header "limits.h": YES
Has header "linux/wireless.h": NO
Has header "memory.h": YES
Has header "netinet/in.h": NO
Has header "netinet/tcp.h": NO
Has header "net/if.h": NO
Has header "net/if/media.h": NO
Has header "stdbool.h": YES
Has header "stddef.h": YES
Has header "stdint.h": YES
Has header "stdlib.h": YES
Has header "strings.h": NO
Has header "string.h": YES
Has header "sys/socket.h": NO
Has header "sys/stat.h": YES
Has header "sys/time.h": NO
Has header "sys/types.h": YES
Has header "unistd.h": NO
Has header "windows.h": YES
Header <stdbool.h> has symbol "_Bool": YES
Checking for function "getifaddrs": NO
Checking for function "gettimeofday": NO
Checking for function "memset": YES
Library Iphlpapi found: YES
Library WS2_32 found: YES
Configuring platform.h using configuration
Build targets in project: 2

Subproject czmq finished.
Downloading cppzmq from https://github.com/zeromq/cppzmq/archive/v4.2.1.zip
Downloading file of unknown size.
Downloading patch from file:///C:/OpenUxAS/3rd/cppzmq-4.2.1_patch.tar
Download size: 10240
Downloading: ..........

Executing subproject cppzmq.

Project name: cppzmq
Native cpp compiler: cl (msvc 19.12.25831)
Build targets in project: 3

Subproject cppzmq finished.
Downloading zyre from https://github.com/zeromq/zyre/archive/v1.1.0.zip
Downloading file of unknown size.
Downloading patch from file:///C:/OpenUxAS/3rd/zyre-1.1.0_patch.tar
Download size: 10240
Downloading: ..........

Executing subproject zyre.

Project name: zyre
Native c compiler: cl (msvc 19.12.25831)
Build targets in project: 4

Subproject zyre finished.
Downloading sqlite3 from https://sqlite.org/2016/sqlite-amalgamation-3120200.zip
Download size: 1882429
Downloading: ..........
Downloading patch from file:///C:/OpenUxAS/3rd/sqlite-amalgamation-3120200_patch.tar
Download size: 10240
Downloading: ..........

Executing subproject sqlite3.

Project name: sqlite3
Native c compiler: cl (msvc 19.12.25831)
Build targets in project: 5

Subproject sqlite3 finished.
Downloading sqlitecpp from https://github.com/SRombauts/SQLiteCpp/archive/1.3.1.zip
Downloading file of unknown size.
Downloading patch from file:///C:/OpenUxAS/3rd/SQLiteCpp-1.3.1_patch.tar
Download size: 10240
Downloading: ..........

Executing subproject sqlitecpp.

Project name: sqlitecpp
Native cpp compiler: cl (msvc 19.12.25831)
Build targets in project: 6

Subproject sqlitecpp finished.
Downloading zlib from https://github.com/madler/zlib/archive/v1.2.8.zip
Downloading file of unknown size.
Downloading patch from file:///C:/OpenUxAS/3rd/zlib-1.2.8_patch.tar
Download size: 10240
Downloading: ..........

Executing subproject zlib.

Project name: zlib
Native c compiler: cl (msvc 19.12.25831)
Build targets in project: 7

Subproject zlib finished.
Downloading minizip from https://github.com/nmoinvaz/minizip/archive/1.2.zip
Downloading file of unknown size.

Meson encountered an error in file meson.build, line 52, column 0:
Subproject directory '3rd\\minizip' does not exist and cannot be downloaded:
Incorrect hash for source minizip:
 50a155989e87cd803f9d58caf6bce14265125b87c52f3edfbe72b412847525cf expected
 e2d113da6e6c22ba0487e9a81a179195b9f41e182b1cf3e843acf53bce794b7c actual.

------------------------------------------------------------------------------------------------------------------

Any useful help with this? Thanks in advance!

**Comment by derekkingston** [comment]
The minizip project upon which OpenUxAS depends has changed and, hence, so did its hash value. You have a couple options: (1) use the latest version of OpenUxAS in the 'develop' branch; (2) manually fix the hash value.

For (1), simply pull the latest: `git clone https://github.com/afrl-rq/OpenUxAS`

For (2), copy the actual reported hash and paste on line 6 in `3rd/minizip.wrap.tmpl`, so that file will be:
```
[wrap-file]

directory = minizip-1.2
source_url = https://github.com/nmoinvaz/minizip/archive/1.2.zip
source_filename = 1.2.zip
source_hash = e2d113da6e6c22ba0487e9a81a179195b9f41e182b1cf3e843acf53bce794b7c

patch_url = %top%/minizip-1.2_patch.tar
patch_filename = minizip-1.2_patch.tar
patch_hash = %patch_hash%
```

Re-run `prepare.py` and then meson: `meson.py build --backend=vs`

**Comment by derekkingston** [comment]
The 0.1 release has been updated to fix this (essentially option 2 from previous comment). You should be able to download the release and follow the steps to get a working version. Note, Windows building is the least reliable, you could have better results with a virtual machine running Linux.
