### ISSUE TITLE
The release build is missing from the configuration manager

### ISSUE THREAD

**Issue by kfu0115** [afrl-rq/OpenUxAS-SoI#60]
Is there a release build of UxAS? I am trying to build it in release mode but the option is missing from Visual Studio.  Is there no release mode of the exe? If so, why?

**Comment by jonsteingass** [comment]
It is possible to generate a release build of OpenUxAS for Visual Studio using meson. With the developer command prompt for VS, navigate to the OpenUxAS root directory and execute the command 'meson.py build --backend=vs --buildtype=release'
