### ISSUE TITLE
cannot find documentation file of example 02

### ISSUE THREAD

**Issue by kqing0515** [afrl-rq/OpenUxAS-SoI#73]
Hi, I couldn't find the document named WaterwayExample_MessageFLow.pdf mentioned in READ.ME for exampe 02 waterwaysearch.

Please give me a hint if I miss something.

Thanks

**Comment by SteveRas** [comment]
There is 'source code' to build the documentation on the directory:
OpenUxAS/doc

To make the documentation a little more accessible, I've created a new repository with pdf files:
https://github.com/afrl-rq/OpenUxAS_Docs

-Steve
