### ISSUE TITLE
Use Copper tool to extract and verify models from UxAS service source code

### ISSUE THREAD

**Issue by sagarchaki** [afrl-rq/OpenUxAS-SoI#9]
Hi Derrick, Could you please create a new branch for me to pursue this work, or advise if a new repository is needed. Thanks -- Sagar

**Comment by sagarchaki** [comment]
Hi Derrick, I wasn't able to push to the "copper" branch. Could you please check the permissions? Thanks -- Sagar

**Comment by derekkingston** [comment]
Sagar, I believe we got this sorted out: there is a `copper` branch to which you should be able to write.
